### PR TITLE
Added more dialogue and characters

### PR DESCRIPTION
**Pull request by owenslo**
Expanded dialogue, added a new character, and added optional objectives that need to be properly implemented into the quest.

### CODE REVIEW

**Comment by jazzij** [comment]
I think this is related to Issue number #13 ?

**Comment by owenslo** [comment]
I have added no voiced dialogue yet. This update does cover Issue #17 though, which I have failed to mention until now. My bad.

**Review by walkerje — APPROVED** [review]
Hey Logan! I am going to go ahead and accept this, however, in the reflection for the week be sure to include specific references to this pull request, including relevant screenshots.

**Comment by owenslo** [comment]
@walkerje could you expand on your comment? It sounds like you want me to add last week's work to this week's reflection. In the week three reflection, I already added several screenshots of what was included in this pull request.

**Pull request merged**
